// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef recursive_fcn_calc_h
#define recursive_fcn_calc_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_win;
#include <FL/Fl_Input.H>
extern Fl_Input *statement_input;
#include <FL/Fl_Output.H>
extern Fl_Output *output_preview;
extern Fl_Output *history_output;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *calc_btn;
#include <FL/Fl_Button.H>
extern Fl_Button *add_fcn_btn;
extern Fl_Button *view_fcns_btn;
extern Fl_Double_Window *add_fcn_win;
extern Fl_Input *fcn_input;
extern Fl_Input *base_case_input;
extern Fl_Input *restriction_input;
extern Fl_Button *cancel_fcn_btn;
extern Fl_Return_Button *fcn_confirm_btn;
extern Fl_Double_Window *view_fcn_win;
extern Fl_Button *fcn_view_back_btn;
extern Fl_Button *view_fcns_add_fcn_btn;
#include <FL/Fl_Pack.H>
extern Fl_Pack *view_fcns_pack;
#ifndef RECURSIVE_FCN_CALC_H
Fl_Double_Window* make_window();
Fl_Double_Window* make_fcn_window();
Fl_Double_Window* make_view_fcn_window();
#endif
#endif
